### PR TITLE
Adjust the signatures of some stubs

### PR DESCRIPTION
**Pull request by nwrkbiz**
Adjust the signatures of some stubs

### CODE REVIEW

**Comment by nwrkbiz** [comment]
Helps to overcome some crashes with emscripten + fltk

**Comment by ghaerr** [comment]
Hello @nwrkbiz,

This is pretty cool! What version of FLTK are you using for the browser and emscripten? You'll have to post some screenshots :)

Let me know when you're ready for commit.

Thank you!

**Comment by nwrkbiz** [comment]
Hi,

I just managed to get the [draw x example from erco](https://www.seriss.com/people/erco/fltk/#FltkX) to work and I am convinced, that all FLTK will work:

image

The FLTK version I use is 1.3.8 and I needed to apply the [XRANDR patch](https://github.com/ghaerr/microwindows/blob/master/src/tools/patch-fltk-1.3.8).

However I needed to change the [SDL2 driver](https://github.com/ghaerr/microwindows/blob/8f1565c3d05c6dc3bdd2909d63e35b0ffbeac96b/src/drivers/scr_sdl2.c#L61) to use the SDL_CreateWindowAndRenderer function rather than creating the window and the renderer one after another. I do not know why and am investigating this now.

Best regards!

**Comment by nwrkbiz** [comment]
Finished now fltk works.

**Comment by ghaerr** [comment]
Thanks for the fixes and screenshots!

**Pull request merged**
